name: pr
on:
  push:
    branches: [develop]
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened

env:
  NEXT_PUBLIC_API_KEY: ${{ secrets.FB_API_KEY}}
  NEXT_PUBLIC_AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN}}
  NEXT_PUBLIC_PROJECT_ID: ${{ secrets.FB_PROJECT_ID}}
  NEXT_PUBLIC_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET}}
  NEXT_PUBLIC_MESSAGING_SENDER_ID: ${{ secrets.FB_MESSAGING_SENDER_ID}}
  NEXT_PUBLIC_APP_ID: ${{ secrets.FB_APP_ID}}
  NEXT_PUBLIC_MEASUREMENT_ID: ${{ secrets.FB_MEASUREMENT_ID}}

jobs:
  Test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v2
      - name: use node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci

      - name: build
        run: npm run build
      - name: 'create env.test file'
        run: |
          cd ./packages/backend/
          touch .env.test
          echo BASE_URL="/api/v1" >> .env.test
          echo VERBOSE=true >> .env.test
      - name: test
        # continue-on-error: true
        run: npm run test
