name: pr
on:
  push:
    branches: [develop]
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened

env:
  NEXT_PUBLIC_API_KEY: AIzaSyCKTAzQpyUGa9AFPaZz2Xs52ipER8inwZM
  NEXT_PUBLIC_AUTH_DOMAIN: count-me-in-stage.firebaseapp.com
  NEXT_PUBLIC_PROJECT_ID: count-me-in-stage
  NEXT_PUBLIC_STORAGE_BUCKET: count-me-in-stage.appspot.com
  NEXT_PUBLIC_MESSAGING_SENDER_ID: 110868769843
  NEXT_PUBLIC_APP_ID: 1:110868769843:web:afc17ec14b623ef5ba4746
  NEXT_PUBLIC_MEASUREMENT_ID: G-KQY4VB7K66

jobs:
  Test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    steps:
      - uses: actions/checkout@v2
      - name: use node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci

      - name: build
        run: npm run build
      - name: test
        continue-on-error: true
        run: npm run test
